name: docker-clang

on:
  push:
    branches:
    - 'main'
    - 'master'
    - 'dev'
    paths-ignore:
    - '**/README.md'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron:  "0 0 1 * *"
  workflow_dispatch:

jobs:
  test:
    name: Test LLVM ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.3", "3.4", "3.4", "3.5", "3.7", "3.8", "3.9", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "dev", "latest"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          tags: silkeh/clang:${{ matrix.version }}
          file: ${{ matrix.version }}.Dockerfile
          push: false
      - name: Run tests
        run: docker run --rm -v "$PWD:/build" silkeh/clang:${{ matrix.version }} /build/tests/run.sh

  push:
    name: Push LLVM ${{ matrix.version }}
    needs: test
    environment: dockerhub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.3", "3.4", "3.4", "3.5", "3.7", "3.8", "3.9", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "dev", "latest"]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          tags: silkeh/clang:${{ matrix.version }}
          file: ${{ matrix.version }}.Dockerfile
          push: true
